<style>
    .headerzone h4 {
        font-family: 'Nunito' !important;
        font-style: italic;
        font-size: 24px;
    }
</style>
<div>
    <div class="row" style="margin:0;">
        <div class="container_noap">
            <div class="row">
                <div class="col-xs-12 vavavoos-header" style="display:none">
                    <div class="vavavoos-user pull-left" style="margin-top: 27px;">
                        <?php if (isset($_SESSION['vavavoos']) && ($_SESSION['vavavoos']['isemployer'] || $_SESSION['vavavoos']['isva'])): ?>
                            LOGGED IN AS: <?php echo $_SESSION['vavavoos']['displayname']; ?>
                            <a href="<?php echo VAMENUPAGE ?>&menu=thanks" class="btn defaultbutton btn-sm">Log off</a>
                        <?php else: ?>
                            <?php if (vavavoos_clean_param($_GET['menu']) != 'managesignon'): ?>
                                <a href="<?php echo VAMENUPAGE . "&menu=managesignon" ?>" class="btn greenbutton">
                                    Log in
                                </a>
                            <?php endif; ?>

                        <?php endif; ?>
                    </div>
                    <div
                        style="<?php if (vavavoos_clean_param($_GET['menu']) != 'managesignon'): ?>float:right<?php endif; ?>">
                        <?php
                        $logo = isset($_GET['fixiemenu']) ? 'fixiesonvavavoos.png' : 'shortlogo.png';
                        ?>
                        <img src="<?php echo VAVAVOOS_PLUGINURL ?>assets/img/<?php echo $logo ?>"
                             style="vertical-align: top;">
                    </div>
                </div>
            </div>
            <br/><br/>

            <div id="va-content">
                <div style="margin-top:40px;text-align: center">
                    <img src="<?php echo VAVAVOOS_PLUGINURL ?>assets/img/loader.gif"/>

                    <div style="margin-top:20px;">
                        <img src="<?php echo VAVAVOOS_PLUGINURL ?>assets/img/shortlogo.png">
                    </div>
                </div>
            </div>
            <hr>
            <footer>
                <p>

                    <a href="http://vavavoos.com">&copy; 2014 - <?php echo date('Y') ?>
                        Vavavoos. All rights reserved.
                    </a>
                </p>
            </footer>

        </div>
    </div>
</div>

<script type="text/javascript">
    vabaseurl = '<?php echo VABASEURL;?>';
    vafixiesbaseurl = '<?php echo VAFIXIESBASEURL;?>';
    loadcontent = function (data) {

        jQuery('.vavavoos-header').fadeIn();
        jQuery('#va-content').html(data);

        jQuery('.timepicker').datetimepicker({
            format: 'LT'
            //pickDate: false
        });

        jQuery('.datepicker').datetimepicker({
            // pickTime: false
            format: 'D/MM/YYYY'
        });
    };

    function varefresh(view, currentmenu) {
        jQuery.ajaxPrefilter(function (options, originalOptions, jqXHR) {
            options.crossDomain = {
                crossDomain: true
            };
            options.xhrFields = {
                withCredentials: true
            };
        });
        <?php
         if(isset($_GET['fixiemenu'])):
            global $uriid;
            $search = isset($_GET['s'])?'?s='.vavavoos_clean_param($_GET['s']):'';
        ?>
        jQuery.ajax({
            url: '<?php echo VAFIXIESBASEURL."getview$search"?>',
            type: 'POST',
            data: {view: view, wpmenu: currentmenu, uriid: '<?php echo $uriid?>'},
            success: loadcontent
        });
        <?php else:?>
        jQuery.ajax({
            url: '<?php echo VABASEURL."getview"?>',
            type: 'POST',
            data: {view: view, wpmenu: currentmenu, va: '<?php echo json_encode($VA);?>'},
            success: loadcontent
        });
        <?php endif;?>
    }
</script>