<style>
    .headerzone h4 {
        font-family: 'Nunito' !important;
        font-style: italic;
        font-size: 24px;
    }
</style>
<div>
    <div class="row" style="margin:0;">
        <div class="container_noap">
            <div class="col-xs-12 vavavoos-header" style="display:none">
                <?php if (isset($_SESSION['vavavoos']) && ($_SESSION['vavavoos']['isemployer'] || $_SESSION['vavavoos']['isva'])): ?>
                    <?php echo $_SESSION['vavavoos']['displayname']; ?>
                    <small>(<a href="<?php echo VAMENUPAGE ?>&menu=thanks">log off</a>)</small>
                <?php else: ?>
                    <small>(<a href="<?php echo VAMENUPAGE . "&menu=managesignon" ?>">log in</a>)</small>
                <?php endif; ?>
                <div style="float:right">
                    <img src="<?php echo VAVAVOOS_PLUGINURL ?>assets/img/shortlogo.png"
                         style="height: 31px;vertical-align: top;">
                </div>
            </div>
            <br/><br/>

            <div id="va-content">
                <div style="margin-top:40px;text-align: center">
                    <img src="<?php echo VAVAVOOS_PLUGINURL ?>assets/img/loader.gif"/>

                    <div style="margin-top:20px;">
                        <img src="<?php echo VAVAVOOS_PLUGINURL ?>assets/img/shortlogo.png">
                    </div>
                </div>
            </div>
            <hr>
            <footer>
                <p>

                    <a href="http://vavavoos.com">&copy; 2014 - <?php echo date('Y') ?>
                        Vavavoos. All rights reserved.
                    </a>
                </p>
            </footer>

        </div>
    </div>
</div>

<script type="text/javascript">
    vabaseurl = '<?php echo VABASEURL;?>';
    function varefresh(view, currentmenu) {
        jQuery.ajaxPrefilter(function (options, originalOptions, jqXHR) {
            options.crossDomain = {
                crossDomain: true
            };
            options.xhrFields = {
                withCredentials: true
            };
        });
        jQuery.ajax({
            url: '<?php echo VABASEURL."getview"?>',
            type: 'POST',
            data: {view: view, wpmenu: currentmenu, va: '<?php echo json_encode($VA);?>'},
            success: function (data) {

                jQuery('.vavavoos-header').fadeIn();
                jQuery('#va-content').html(data);

                jQuery('.timepicker').datetimepicker({
                    format: 'LT'
                    //pickDate: false
                });

                jQuery('.datepicker').datetimepicker({
                    // pickTime: false
                    format: 'D/MM/YYYY'
                });
            }
        });
    }
</script>